name: Poetry install and pytest
on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.py"
      - "**.yaml"
      - "**.yml"
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - "**.yaml"
      - "**.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Add Poetry to PATH
      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Cache Poetry's dependencies based on the lock file
      - name: Set up Poetry cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      # Install dependencies using Poetry
      - name: Install dependencies
        run: poetry install

      # Run unit tests using Poetry
      - name: Run unit tests
        run: poetry run pytest --cov=gpt_engineer
