name: Validate agent protocol compliance
on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.py"
      - "**.yaml"
      - "**.yml"
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - "**.yaml"
      - "**.yml"

jobs:
  publish:
    name: Validate agent protocol compliance
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install agent requirements
        run: pip install .

      - name: Check existence of OPENAI_API_KEY
        run: |
          if [[ -z "${OPENAI_API_KEY}" ]]; then
            echo "OPENAI_API_KEY is empty"
          else
            echo "OPENAI_API_KEY has a length of ${#OPENAI_API_KEY}"
          fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run agent and validate compliance
        run: |
          python gpt_engineer/api.py & # Make sure to use the ampersand to detach your agent
          URL=http://127.0.0.1:8000 bash -c "$(curl -fsSL https://agentprotocol.ai/test.sh)"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
