name: Validate agent protocol compliance
on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.py"
      - "**.yaml"
      - "**.yml"
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - "**.yaml"
      - "**.yml"

jobs:
  publish:
    name: Validate agent protocol compliance
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install agent requirements
        run: pip install -r requirements.txt

      - name: Run agent and validate compliance
        run: |
          <command to run your agent> & # Make sure to use the ampersand to detach your agent
          URL=http://127.0.0.1:8000 bash -c "$(curl -fsSL https://agentprotocol.ai/test.sh)"
